generator: admingenerator.generator.doctrine
params:
  model: Shaduli\BlogBundle\Entity\Post
  namespace_prefix: Acme
  bundle_name: Bundle\BlogBundle
  fields: ~

builders:
  list:
    params:
      title: List for Bundle\BlogBundle
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: New object for Bundle\BlogBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ YourModel.title }}"
      display: ~
      actions:
        list: ~
  delete: ~
