comment:
    pattern:  /
    defaults: { _controller: "BlogBundle:Link:index" }

comment_show:
    pattern:  /{id}/show
    defaults: { _controller: "BlogBundle:Link:show" }

comment_new:
    pattern:  /new
    defaults: { _controller: "BlogBundle:Link:new" }

comment_create:
    pattern:  /create
    defaults: { _controller: "BlogBundle:Link:create" }
    requirements: { _method: post }

comment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BlogBundle:Link:edit" }

comment_update:
    pattern:  /{id}/update
    defaults: { _controller: "BlogBundle:Link:update" }
    requirements: { _method: post }

comment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BlogBundle:Link:delete" }
    requirements: { _method: post }
