Shaduli\BlogBundle\Entity\Category:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: '100'
    description:
      type: string
      length: '1000'
  lifecycleCallbacks: {  }
