BlogBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BlogBundle:Default:index }
BlogBundle_post:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /post